<template>
  <div style="width:100%;height:100%">
    <div id="mapNode" >

    </div>
  </div>
</template>

<script>
import * as esriLoader from 'esri-loader'
export default {
  name: 'gisMod',
  data () {
    let test_slsz =
    [
    {
        "ADAG": "太湖流域水环境监测中心",
        "MNAG": "",
        "LGTD": "120.10861",
        "BSNM": "长江",
        "NT": "",
        "STNM": "龚巷桥",
        "WFRCD": "",
        "STLC": "江苏武进雪堰镇龚巷村",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320400",
        "STCD": "50000002",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "武进港",
        "LTTD": "31.505556",
        "id": "50000002",
        "index": 2
    },
    {
        "ADAG": "太湖流域水环境监测中心",
        "MNAG": "",
        "LGTD": "120.01111",
        "BSNM": "长江",
        "NT": "t1",
        "STNM": "杨家浦桥",
        "WFRCD": "",
        "STLC": "浙江省长兴县杨家浦村",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "330400",
        "STCD": "50000004",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "杨家浦港",
        "LTTD": "31.019444",
        "id": "50000004",
        "index": 4
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "胥江大桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000006",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000006",
        "index": 5
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "铜坑闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000007",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000007",
        "index": 6
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "联湖桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000008",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000008",
        "index": 7
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "濮溇闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000009",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000009",
        "index": 8
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "汤溇闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000010",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000010",
        "index": 9
    },
    {
        "ADAG": "",
        "MNAG": "",
        "LGTD": "120.200043",
        "BSNM": "",
        "NT": "t1",
        "STNM": "梅梁湖泵站",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "",
        "ADDVCD": "",
        "STCD": "50000011",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "LTTD": "31.525873",
        "id": "50000011",
        "index": 10
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "景宜桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000012",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000012",
        "index": 11
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "杨家桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000013",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000013",
        "index": 12
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t1",
        "STNM": "大港桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000014",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "50000014",
        "index": 13
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "夏港闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000015",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "夏港河",
        "id": "50000015",
        "index": 14
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "墅沟闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000016",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "新槎浦",
        "id": "50000016",
        "index": 15
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "新川沙",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000017",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "新川沙河",
        "id": "50000017",
        "index": 16
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "新石洞",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000018",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "马路河",
        "id": "50000018",
        "index": 17
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "五好沟",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000019",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "随塘河",
        "id": "50000019",
        "index": 18
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t2",
        "STNM": "外高桥泵",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000020",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "浦东外环运河",
        "id": "50000020",
        "index": 19
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "石浦大桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000021",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "吴淞江",
        "id": "50000021",
        "index": 20
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "太和大桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000022",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "浏河",
        "id": "50000022",
        "index": 21
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "浏岛大桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000023",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "浏河",
        "id": "50000023",
        "index": 22
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "汤溇",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000024",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "太湖南部沿岸区",
        "id": "50000024",
        "index": 23
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "朱枫公路和尚泾桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000025",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "范塘－和尚泾",
        "id": "50000025",
        "index": 24
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "曹芳泾桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000026",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "曹芳泾",
        "id": "50000026",
        "index": 25
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "頔塘苏浙交界处",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000027",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "頔塘",
        "id": "50000027",
        "index": 26
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "升罗桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000028",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "长三港",
        "id": "50000028",
        "index": 27
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t4",
        "STNM": "九里村桥",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000029",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "澜溪塘",
        "id": "50000029",
        "index": 28
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t5",
        "STNM": "甘歧水库",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000030",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "甘歧水库",
        "id": "50000030",
        "index": 29
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t7",
        "STNM": "北窑港枢纽",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000031",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "太浦河",
        "id": "50000031",
        "index": 30
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t7",
        "STNM": "虞山船闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000032",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "望虞河",
        "id": "50000032",
        "index": 31
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t7",
        "STNM": "入滆湖口",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000033",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "新孟河",
        "id": "50000033",
        "index": 32
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "t7",
        "STNM": "入太湖口",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "50000034",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "新孟河",
        "id": "50000034",
        "index": 33
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.12466",
        "BSNM": "长江流域",
        "NT": "t4",
        "STNM": "三里桥",
        "WFRCD": "10024",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120300",
        "ADDVCD": "330400",
        "STCD": "50000037",
        "STGRD": "",
        "HNNM": "太湖流域苕溪水系",
        "RVNM": "泗安塘",
        "LTTD": "30.85433",
        "id": "50000037",
        "index": 34
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "长江流域",
        "NT": "t4",
        "STNM": "金泽大桥（浙江嘉善）",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "F120400",
        "ESSTYM": "",
        "ADDVCD": "310000",
        "STCD": "50000038",
        "STGRD": "",
        "HNNM": "太湖流域杭嘉湖区水系",
        "RVNM": "太浦河",
        "id": "50000038",
        "index": 35
    },
    {
        "ADAG": "浙江省水文局",
        "MNAG": "",
        "LGTD": "120.03333",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "杨家埠",
        "WFRCD": "",
        "STLC": "浙江省湖州市龙溪乡杨家埠",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "330400",
        "STCD": "63010800",
        "STGRD": "",
        "HNNM": "太湖流域苕溪水系",
        "RVNM": "旄儿港",
        "LTTD": "30.9",
        "id": "63010800",
        "index": 36
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "119.576385",
        "BSNM": "长江流域",
        "NT": "wq",
        "STNM": "杨桥",
        "WFRCD": "F1201201004000",
        "STLC": "浙江湖州长兴县",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "330400",
        "STCD": "63080010",
        "STGRD": "",
        "HNNM": "太湖流域苕溪水系",
        "RVNM": "泗安水库上游",
        "LTTD": "30.932499",
        "id": "63080010",
        "index": 37
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "119.94",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "棉堤桥",
        "WFRCD": "F1201103514000",
        "STLC": "江苏宜兴",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63180030",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "烧香港",
        "LTTD": "31.373611",
        "id": "63180030",
        "index": 39
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "119.9425",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "社渎港桥",
        "WFRCD": "F1201103714000",
        "STLC": "江苏宜兴",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63180040",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "社渎港",
        "LTTD": "31.35639",
        "id": "63180040",
        "index": 40
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "119.93083",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "官渎港桥",
        "WFRCD": "",
        "STLC": "江苏宜兴",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63180045",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "官渎港",
        "LTTD": "31.341112",
        "id": "63180045",
        "index": 41
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "119.92194",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "大浦港桥",
        "WFRCD": "F1201101614000",
        "STLC": "江苏宜兴",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63180055",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "大浦港",
        "LTTD": "31.313889",
        "id": "63180055",
        "index": 42
    },
    {
        "ADAG": "江苏省水文水资源勘测局",
        "MNAG": "",
        "LGTD": "119.48555",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "团结桥",
        "WFRCD": "",
        "STLC": "溧阳市团结桥",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320400",
        "STCD": "63186600",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "南河",
        "LTTD": "31.42389",
        "id": "63186600",
        "index": 43
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.345",
        "BSNM": "",
        "NT": "自动站",
        "STNM": "贡湖自动站",
        "WFRCD": "104408",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63189001",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖贡湖水体",
        "LTTD": "31.408",
        "id": "63189001",
        "index": 44
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.63",
        "BSNM": "",
        "NT": "自动站",
        "STNM": "望亭自动站",
        "WFRCD": "10415",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63189002",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "望虞河干流",
        "LTTD": "31.654",
        "id": "63189002",
        "index": 45
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.7",
        "BSNM": "",
        "NT": "自动站",
        "STNM": "常熟自动站",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63189003",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "",
        "LTTD": "31.5",
        "id": "63189003",
        "index": 46
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.5",
        "BSNM": "",
        "NT": "自动站",
        "STNM": "金泽自动站",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63189005",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "LTTD": "31.2",
        "id": "63189005",
        "index": 48
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.43",
        "BSNM": "",
        "NT": "自动站",
        "STNM": "张桥自动站",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63189008",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "LTTD": "31.5",
        "id": "63189008",
        "index": 51
    },
    {
        "ADAG": "江苏省水文水资源勘测局",
        "MNAG": "",
        "LGTD": "119.933334",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "洪巷港桥",
        "WFRCD": "",
        "STLC": "宜兴市大浦镇",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63195040",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "洪巷港",
        "LTTD": "31.333334",
        "id": "63195040",
        "index": 53
    },
    {
        "ADAG": "江苏省水文水资源勘测局",
        "MNAG": "",
        "LGTD": "120.03333",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "分水",
        "WFRCD": "",
        "STLC": "宜兴市分水镇",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63195120",
        "STGRD": "",
        "HNNM": "太湖流域南溪水系",
        "RVNM": "太滆运河",
        "LTTD": "31.5",
        "id": "63195120",
        "index": 54
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "大港",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63200100",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63200100",
        "index": 55
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "洪巷",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201110",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201110",
        "index": 57
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "官渎",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201120",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201120",
        "index": 58
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "社渎",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201130",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201130",
        "index": 59
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "汤溇闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201620",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201620",
        "index": 61
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "濮溇闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201650",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201650",
        "index": 62
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "幻溇闸",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63201750",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63201750",
        "index": 63
    },
    {
        "ADAG": "",
        "MNAG": "",
        "LGTD": "120.475388",
        "BSNM": "长江",
        "NT": "syd",
        "STNM": "吴江水厂取水口",
        "WFRCD": "F1201300211000",
        "STLC": "",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63203333",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "东太湖",
        "LTTD": "31.015867",
        "id": "63203333",
        "index": 67
    },
    {
        "ADAG": "江苏水利",
        "MNAG": "",
        "LGTD": "119.933334",
        "BSNM": "长江",
        "NT": "t2",
        "STNM": "圩塘闸",
        "WFRCD": "",
        "STLC": "苏-常州",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63203520",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "澡港河",
        "LTTD": "31.95",
        "id": "63203520",
        "index": 71
    },
    {
        "ADAG": "常州市水利局",
        "MNAG": "",
        "BSNM": "长江",
        "NT": "t2",
        "STNM": "澡港闸（闸下游）",
        "WFRCD": "",
        "STLC": "江苏省常州市新北区春江镇",
        "WDSTYM": "",
        "WRRCD": "F120100",
        "ESSTYM": "",
        "ADDVCD": "320400",
        "STCD": "63203521",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "澡港河",
        "id": "63203521",
        "index": 72
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "琳桥（西）",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63203860",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63203860",
        "index": 73
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "永昌泾",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63204210",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63204210",
        "index": 74
    },
    {
        "ADAG": "",
        "MNAG": "",
        "BSNM": "",
        "NT": "",
        "STNM": "冶长泾",
        "WFRCD": "",
        "STLC": "",
        "WDSTYM": "",
        "WRRCD": "",
        "ESSTYM": "",
        "ADDVCD": "",
        "STCD": "63204220",
        "STGRD": "",
        "HNNM": "",
        "RVNM": "",
        "id": "63204220",
        "index": 75
    },
    {
        "ADAG": "太湖局",
        "MNAG": "",
        "LGTD": "121.13611",
        "BSNM": "长江流域",
        "NT": "wq",
        "STNM": "娄陆大桥",
        "WFRCD": "",
        "STLC": "太仓陆渡镇",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320500",
        "STCD": "63205020",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "浏河",
        "LTTD": "31.467222",
        "id": "63205020",
        "index": 81
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.12",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "湖山桥",
        "WFRCD": "F1202101713013",
        "STLC": "江苏无锡",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320200",
        "STCD": "63280010",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "直湖港",
        "LTTD": "31.512777",
        "id": "63280010",
        "index": 84
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.08917",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "雅浦港桥",
        "WFRCD": "",
        "STLC": "江苏常州武进",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320400",
        "STCD": "63280030",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "雅浦港",
        "LTTD": "31.462778",
        "id": "63280030",
        "index": 85
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.257225",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J03#五里湖",
        "WFRCD": "",
        "STLC": "五里湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280110",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖五里湖水体",
        "LTTD": "31.507778",
        "id": "63280110",
        "index": 86
    },
    {
        "ADAG": "太湖局",
        "MNAG": "",
        "LGTD": "120.23278",
        "BSNM": "长江流域",
        "NT": "t6",
        "STNM": "西五里湖",
        "WFRCD": "",
        "STLC": "五里湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280111",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖五里湖水体",
        "LTTD": "31.538332",
        "id": "63280111",
        "index": 87
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.22806",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J06#梅园",
        "WFRCD": "F1201300413011",
        "STLC": "五里湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280120",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖梅梁湖水体",
        "LTTD": "31.538055",
        "id": "63280120",
        "index": 88
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.21139",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "B20#小湾里",
        "WFRCD": "F1201300413011",
        "STLC": "梅梁湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280121",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖梅梁湖水体",
        "LTTD": "31.465557",
        "id": "63280121",
        "index": 89
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.133606",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J11#闾江口",
        "WFRCD": "F1201300413011",
        "STLC": "梅梁湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280122",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖梅梁湖水体",
        "LTTD": "31.494167",
        "id": "63280122",
        "index": 90
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.16417",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J15#拖山",
        "WFRCD": "F1201300413011",
        "STLC": "梅梁湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280123",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖梅梁湖水体",
        "LTTD": "31.405832",
        "id": "63280123",
        "index": 91
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.19556",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J16#三号标",
        "WFRCD": "F1201300413011",
        "STLC": "梅梁湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280124",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖梅梁湖水体",
        "LTTD": "31.507778",
        "id": "63280124",
        "index": 92
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.05361",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J12#竺山湖",
        "WFRCD": "F1201300211001",
        "STLC": "竺山湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280130",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖竺山湖水体",
        "LTTD": "31.441666",
        "id": "63280130",
        "index": 93
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.24027",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "B21#渔业村",
        "WFRCD": "F1201300211002",
        "STLC": "太湖贡湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280141",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖贡湖水体",
        "LTTD": "31.404999",
        "id": "63280141",
        "index": 95
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.29722",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "J17A#大贡山",
        "WFRCD": "F1201300211002",
        "STLC": "太湖贡湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280142",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖贡湖水体",
        "LTTD": "31.371666",
        "id": "63280142",
        "index": 96
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.36806",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "B23#贡湖",
        "WFRCD": "F1201300211002",
        "STLC": "太湖贡湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280143",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖贡湖水体",
        "LTTD": "31.404167",
        "id": "63280143",
        "index": 97
    },
    {
        "ADAG": "水利部太湖流域管理局",
        "MNAG": "",
        "LGTD": "120.491104",
        "BSNM": "长江",
        "NT": "wq",
        "STNM": "B25#戗港外",
        "WFRCD": "F1201300211000",
        "STLC": "东太湖水体",
        "WDSTYM": "",
        "ESSTYM": "",
        "WRRCD": "F120100",
        "ADDVCD": "320000",
        "STCD": "63280153",
        "STGRD": "",
        "HNNM": "太湖流域湖区水系",
        "RVNM": "太湖东太湖水体",
        "LTTD": "31.077778",
        "id": "63280153",
        "index": 100
    }
    ];
    let pwkArray = [{"OBJECTID":"17","名称":"嘉善大成环保有限公司","X":"120.95917","Y":"30.97722","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=17&stcd=17&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"嘉善大成环保有限公司"},{"OBJECTID":"18","名称":"嘉善枫南金鑫丝绸印染厂","X":"121.00333","Y":"30.88444","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=18&stcd=18&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"嘉善枫南金鑫丝绸印染厂"},{"OBJECTID":"19","名称":"嘉善华星纸业有限公司","X":"120.98306","Y":"30.99611","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=19&stcd=19&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"嘉善华星纸业有限公司"},{"OBJECTID":"20","名称":"昆山方元水处理公司石浦污水","X":"121.05194","Y":"31.26056","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=20&stcd=20&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山方元水处理公司石浦污水"},{"OBJECTID":"21","名称":"昆山金星镀锌有限公司","X":"121.000328","Y":"31.257275","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=21&stcd=21&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山金星镀锌有限公司"},{"OBJECTID":"22","名称":"昆山锦溪污水处理厂","X":"120.93861","Y":"31.17694","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=22&stcd=22&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山锦溪污水处理厂"},{"OBJECTID":"23","名称":"昆山昆鹏环境技术有限公司","X":"120.99694","Y":"31.24806","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=23&stcd=23&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山昆鹏环境技术有限公司"},{"OBJECTID":"25","名称":"昆山千灯富民工业区污水处理厂","X":"121.035","Y":"31.28278","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=25&stcd=25&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山千灯富民工业区污水处理厂"},{"OBJECTID":"26","名称":"昆山市华新电路板公司","X":"120.99778","Y":"31.26028","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=26&stcd=26&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山市华新电路板公司"},{"OBJECTID":"27","名称":"昆山市千灯陶桥印制线路板厂","X":"120.99333","Y":"31.22306","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=27&stcd=27&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山市千灯陶桥印制线路板厂"},{"OBJECTID":"28","名称":"昆山市千灯吴桥电器厂","X":"120.99528","Y":"31.23694","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=28&stcd=28&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山市千灯吴桥电器厂"},{"OBJECTID":"29","名称":"昆山万正电路板有限公司","X":"120.99694","Y":"31.25583","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=29&stcd=29&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山万正电路板有限公司"},{"OBJECTID":"30","名称":"昆山新苑污水处理有限公司","X":"121.02083","Y":"31.17194","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=30&stcd=30&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山新苑污水处理有限公司"},{"OBJECTID":"31","名称":"昆山瀛浦热电有限公司","X":"121.05389","Y":"31.27028","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=31&stcd=31&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"昆山瀛浦热电有限公司"},{"OBJECTID":"32","名称":"平湖市神光（天神）皮革有限公","X":"121.10056","Y":"30.81889","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=32&stcd=32&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"平湖市神光（天神）皮革有限公司"},{"OBJECTID":"36","名称":"上海嘉乐股份有限公司染整部","X":"121.18194","Y":"30.79167","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=36&stcd=36&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"上海嘉乐股份有限公司染整部"},{"OBJECTID":"37","名称":"上海金山枫泾水质净化有限公司","X":"121.02556","Y":"30.89667","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=37&stcd=37&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"上海金山枫泾水质净化有限公司"},{"OBJECTID":"38","名称":"上海青浦大观园污水处理厂","X":"120.90917","Y":"31.06917","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=38&stcd=38&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"上海青浦大观园污水处理厂"},{"OBJECTID":"39","名称":"盛泽水处理发展有限公司四公司","X":"120.67833","Y":"30.90167","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=39&stcd=39&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"盛泽水处理发展有限公司四公司(镇东污水)"},{"OBJECTID":"40","名称":"盛泽水处理发展有限公司五公司","X":"120.68278","Y":"30.89444","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=40&stcd=40&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"盛泽水处理发展有限公司五公司(永前纺织)"},{"OBJECTID":"42","名称":"太仓金源污水处理有限公司","X":"121.12861","Y":"31.47889","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=42&stcd=42&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"太仓金源污水处理有限公司"},{"OBJECTID":"43","名称":"桐乡福利造纸厂","X":"120.47778","Y":"30.73667","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=43&stcd=43&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"桐乡福利造纸厂"},{"OBJECTID":"5","名称":"东方绿洲污水处理厂","X":"120.99306","Y":"31.10056","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=5&stcd=5&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"东方绿洲污水处理厂"},{"OBJECTID":"52","名称":"吴江市桃源污水处理厂","X":"120.48111","Y":"30.8225","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=52&stcd=52&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"吴江市桃源污水处理厂"},{"OBJECTID":"53","名称":"吴江市铜罗助剂厂","X":"120.51306","Y":"30.85361","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=53&stcd=53&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"吴江市铜罗助剂厂"},{"OBJECTID":"54","名称":"吴江桃源镇铜罗东方污水处理厂","X":"120.54333","Y":"30.85944","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=54&stcd=54&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"吴江桃源镇铜罗东方污水处理厂"},{"OBJECTID":"6","名称":"工行青浦培训中心","X":"120.895","Y":"31.09028","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=6&stcd=6&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"工行青浦培训中心"},{"OBJECTID":"63","名称":"浙江凌龙纺织有限公司","X":"120.84917","Y":"30.94583","OFFSETX":"-13","OFFSETY":"5","SYMBOLGROUP":"行业一","SYMBOL":"pwk1","URLparam":"?id=63&stcd=63&spt=201612","HEIGHT":"208","WIDTH":"300","TITLE":"浙江凌龙纺织有限公司"}];

    return {
      msg: 'Welcome to Your Vue.js App',
      'szStationList':test_slsz,
      'pwdStationList':pwkArray,
    }
  },
  mounted:function(){
    this.initGisMap();
  },
  methods:{
    initEsriLoader:function(){
      esriLoader.bootstrap((err) => {
        if (err) {
          // handle any loading errors
          console.error(err);
        } else {
          // optionall execute any code once it's preloaded
        }
      }, {
        // use a specific version instead of latest 4.x
        url: 'http://10.1.102.143/arcgis_js_api/3.18/init.js'
      });
    },
    initGisMap:function(){
      this.initEsriLoader();
      esriLoader.dojoRequire(["gowa/gisObject"], (gisObject) => {
      // create map with the given options at a DOM node w/ id 'mapNode'
      // alert('wxcwater');
      let newGisObject = new gisObject({
      baseInfoLayers:[
                {
                   name   : '底图',
                   id : 'backUpLayer',
                   url : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_basemap2/MapServer",
                   layerType:'',
                   useType:'basic',
                   visible:true,
                   contentType:'Polygon'
                },{
                   name   : '引江济太',
                   id : 'yjjtLayer',
                   url : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_wytf/MapServer",
                   layerType:'',
                   useType:'basic',
                   visible:false,
                   contentType:'Polygon'
                },{
                   name   : '主要河流',
                   id : 'mainRiver',
                   url : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_river/MapServer",
                   layerType:'',
                   visible:false,
                   useType:'basic',
                   contentType:'Line'
                },{
                   name   : '水利分区',
                   id : 'waterZone',
                   url : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_shuilifenqu/MapServer",
                   layerType:'',
                   visible:false,
                   useType:'basic',
                   contentType:'Polygon'
                },{
                   name   : '行政分区界限',
                   id : 'xzqZone',
                   url : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_xzfenqujiexian/MapServer",
                   layerType:'',
                   visible:false,
                   useType:'basic',
                   contentType:'Polygon'
                }
              ],
               centerPt:[120.50,31.2],
                xzqUrl : "http://10.1.102.129:6080/arcgis/rest/services/taihu/th_basemap/MapServer"
      },'mapNode',null);
       newGisObject.initMap('mapNode');
      // newGisObject.initGoogleMap();
      this.newGisObject = newGisObject;
      this.addszStationToMap();
      this.addpwkStationToMap();
      // newGisObject.mapObject.setLevel(1);
      });
    },
    addszStationToMap:function(){
      esriLoader.dojoRequire(["esri/symbols/SimpleMarkerSymbol", "esri/geometry/Point", "esri/graphic","esri/SpatialReference",
               "esri/symbols/Font","esri/Color","esri/symbols/TextSymbol","esri/symbols/PictureMarkerSymbol",
               "esri/layers/GraphicsLayer","esri/layers/FeatureLayer","esri/config"],(SimpleMarkerSymbol, Point, Graphic,SpatialReference,Font,Color,
               TextSymbol, PictureMarkerSymbol,GraphicsLayer,FeatureLayer, esriConfig)=>{
                 let graphicsLayer_sz_l1 = new GraphicsLayer();
                 graphicsLayer_sz_l1.id = 'graphicsLayer_sz_l1';
                 graphicsLayer_sz_l1.visible = true;
                 graphicsLayer_sz_l1.on("mouse-over",function(e){
                   // sztooltip(e);
                 });
                 this.newGisObject.addNewLayer('Point',graphicsLayer_sz_l1);
                 var stationSymbol1 = new PictureMarkerSymbol('../gis/assets/sz1.png',20,20);
                 var stationSymbol2 = new PictureMarkerSymbol('../gis/assets/sz2.png',20,20);
                 var stationSymbol3 = new PictureMarkerSymbol('../gis/assets/sz3.png',20,20);
                 var stationSymbol4 = new PictureMarkerSymbol('../gis/assets/sz4.png',20,20);
                 for(var i = 0;i<this.szStationList.length;i++){
                   var targetData = this.szStationList[i];
                   var m = this.newGisObject.lonLat2Mercator([targetData.LGTD,targetData.LTTD]);
                   var p = new Point(targetData.LGTD,targetData.LTTD);
                   var gra ;
                   var testS ;
                   switch(i%10){
                     case 0:gra = new Graphic(p,stationSymbol1,targetData);graphicsLayer_sz_l1.add(gra);break;
                     case 1:gra = new Graphic(p,stationSymbol2,targetData);graphicsLayer_sz_l1.add(gra);break;
                     case 2:gra = new Graphic(p,stationSymbol3,targetData);graphicsLayer_sz_l1.add(gra);break;
                     case 3:gra = new Graphic(p,stationSymbol4,targetData);graphicsLayer_sz_l1.add(gra);break;

                   }
                 }
               })
    },
    addpwkStationToMap:function(){
      esriLoader.dojoRequire(["esri/symbols/SimpleMarkerSymbol", "esri/geometry/Point", "esri/graphic","esri/SpatialReference",
               "esri/symbols/Font","esri/Color","esri/symbols/TextSymbol","esri/symbols/PictureMarkerSymbol",
               "esri/layers/GraphicsLayer","esri/layers/FeatureLayer","esri/config"],(SimpleMarkerSymbol, Point, Graphic,SpatialReference,Font,Color,
               TextSymbol, PictureMarkerSymbol,GraphicsLayer,FeatureLayer, esriConfig)=>{
                 let graphicsLayer_sz_l1 = new GraphicsLayer();
                 graphicsLayer_sz_l1.id = 'graphicsLayer_pwk';
                 graphicsLayer_sz_l1.visible = true;
                 graphicsLayer_sz_l1.on("mouse-over",function(e){
                   // sztooltip(e);
                 });
                 this.newGisObject.addNewLayer('Point',graphicsLayer_sz_l1);
                 var stationSymbol1 = new PictureMarkerSymbol('../gis/assets/pwk.png',10,10);
                 for(var i = 0;i<this.pwdStationList.length;i++){
                   var targetData = this.pwdStationList[i];
                   var m = this.newGisObject.lonLat2Mercator([targetData.LGTD,targetData.LTTD]);
                   var p = new Point(targetData.X,targetData.Y);
                   var gra ;
                   var testS ;

                    gra = new Graphic(p,stationSymbol1,targetData);graphicsLayer_sz_l1.add(gra);


                 }
               })
    }
  }
}
</script>

<style>
@import url('http://10.1.102.143/arcgis_js_api/3.18/esri/css/esri.css');
  #mapNode{

    width: 100%;
    height: 100%;
  }

</style>
